    xavierl_devenv_img:        
        build: ./docker/build/
        ports:
            - "2222:22"
            - "80:80"
        volumes:
            - ./src:/var/www/html
        container_name: xavierl_devenv_ctn



